jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write        # ← обязательно!
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Build
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release

      - name: Pack
        run: dotnet pack MyLibSolution/MyLibSolution.csproj \
          --configuration Release --no-build

      - name: Push to GitHub Packages
        run: dotnet nuget push MyLibSolution/bin/Release/*.nupkg \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          --source "https://nuget.pkg.github.com/MKudryash/index.json"
